import sys
import os
from unittest import mock
import pytest

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../src")))

from snake_game.food import Food


@pytest.fixture
def food():
    with mock.patch("snake_game.food.Turtle") as mock_turtle:
        return Food()


def test_food_init(food):
    assert food.shape() == "circle"
    assert food.speed() == 0  # fastest
    assert food.color() == ("green", "green")
    assert food.shapesize() == (0.5, 0.5, 1)
    assert food.isvisible() is True


def test_food_refresh(food, monkeypatch):
    # Mock random values generated by random.randint
    random_x = 100
    random_y = 150

    # Mock the random.randint function
    def mock_randint(min_value, max_value):
        # Return mock values based on the call order
        return random_x, random_y

    def mock_goto(x, y):
        return (x, y)

    # Apply the monkeypatch to the random.randint function
    monkeypatch.setattr("random.randint", mock_randint)

    # Apply the monkeypatch to the foog.goto method
    monkeypatch.setattr(food, "goto", mock_goto)

    # Call the refresh method, which should use the mocked random values
    food.refresh()

    # Check if the mock_goto was called with the correct arguments
    assert food.goto(random_x, random_y) == (random_x, random_y)
